# Generated by Django 5.2.15 on 2026-06-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_reservation_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_reference',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reserved for a future refundable deposit step.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
