# Generated by Django 5.2.15 on 2026-06-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_reservation_booking_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='name_el',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='description_el',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='route',
            name='duration_el',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='title_el',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
