# Generated by Django 5.2.15 on 2026-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bike_name_el_route_description_el_route_duration_el_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
