# Generated by Django 5.2.15 on 2026-06-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_reservation_confirmation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
