# Generated by Django 5.2.15 on 2026-06-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_reservation_return_deposit_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo shown on the homepage and booking page.', null=True, upload_to='bikes/'),
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='distance_el',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='points_of_interest',
            field=models.TextField(blank=True, default='', help_text='Comma-separated highlights (e.g. White Tower, Aristotelous Square).'),
        ),
        migrations.AddField(
            model_name='route',
            name='points_of_interest_el',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(help_text='Short route summary shown on the routes page.'),
        ),
    ]
