# Generated by Django 5.2.15 on 2026-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_bike_image_route_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='beach_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='beach_info_el',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='coffee_stop',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='route',
            name='coffee_stop_el',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional cover photo for the route card.', null=True, upload_to='routes/'),
        ),
        migrations.AddField(
            model_name='route',
            name='restaurant',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='route',
            name='restaurant_el',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
